[package]
name = "preproc"
version = "0.0.0"
edition = "2018"

[dependencies]
serde = "1.0.130"
serde_json = "1.0.67"
bincode = "1.3.3"
ureq = { version = "2.2.0", features = ["json"] }
fst = "0.4.7"
csv = "1.1"