#ifndef predict_rs
#define predict_rs

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct WordPredictions {
  int len;
  char **words;
} WordPredictions;

struct WordPredictions *rust_function(void);

struct WordPredictions *get_word_predictions(char *characters);

#endif /* predict_rs */
