#ifndef predict_rs
#define predict_rs

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void rust_function(void);

#endif /* predict_rs */
